spring:
  application:
    name: showsdb-auth-server
  # DATASOURCE (MYSQL 8.0)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:61763/showsDB?useSSL=false&serverTimezone=CET
    username: root
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
server:
  port: 9000