spring:
  application:
    name: showsdb-auth-server

  config:
    import: "optional:vault://"
  cloud:
    config:
      enabled: false
    vault:
      enabled: true
      uri: "http://vault-server:8200"
      authentication: token
      token: hvs.Ew61KtKvPqj5AgLE9MQjYKqN
      kv:
        enabled: true
        default-context: client-info
        backend: kv

  # DATASOURCE (MYSQL 8.0)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/showsDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
    username: ${db-user}
    password: ${db-password}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
server:
  port: 9000
showsdb:
  security:
    client:
      client-uri: "http://${IP}:8080"
      client-id: ${client-id}
      client-secret: ${client-secret}
      issuer-uri: "http://auth-server:9000"

logging:
  level:
    org:
      springframework:
        security: debug