spring:
  application:
    name: showsdb-auth-server
  # DATASOURCE (MYSQL 8.0)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8083/showsDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
    username: root
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
server:
  port: 9000
showsdb:
  security:
    client:
      client-id: client-showsdb
      client-secret: $2a$12$25K8LCD..msD33xQ3ht8i.uOjPSxMGtvqWSrmS51mnz1vWv//f2ya