spring:
  application:
    name: showsdb-auth-server

  config:
    import: "optional:vault://"
  cloud:
    config:
      enabled: false
    vault:
      enabled: true
      uri: "http://localhost:8200"
      authentication: token
      token: hvs.Ew61KtKvPqj5AgLE9MQjYKqN
      kv:
        enabled: true
        default-context: client-info
        backend: kv

  # DATASOURCE (MYSQL 8.0)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8083/showsDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
    username: ${db-user}
    password: ${db-password}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
server:
  port: 9000
showsdb:
  security:
    client:
      client-id: ${client-id}
      client-secret: ${client-secret}