spring:
  application:
    name: ShowsDB

  config:
    import: "optional:vault://"
  cloud:
    config:
      enabled: false
    vault:
      enabled: true
      uri: "http://${IP}:8200"
      authentication: token
      token: hvs.Ew61KtKvPqj5AgLE9MQjYKqN
      kv:
        enabled: true
        default-context: client-info
        backend: kv

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB-PATH}/showsDB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
    username: ${db-user}
    password: ${db-password}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    changelog: classpath:db/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${IP}:9000"
      client:
        registration:
          client-showsdb:
            provider: spring
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "http://${IP}:8080/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-showsdb
        provider:
          spring:
            issuer-uri: "http://${IP}:9000"

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method

  api-docs:
    enabled: true

  kafka:
    bootstrap-servers: "http://${IP}:${KAFKA_PORT}"

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

  graphql:
    graphiql:
      enabled: true

  data:
    redis:
      host: ${IP}
      port: 6379
      ttl: 10000

logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        SQL: debug

showsdb:
  env: ${ENV}
  files: ${FILES_PATH}