spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8083/showsDB?useSSL=false&serverTimezone=CET
    username: root
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        # allows for the use of MySQL reserved words as property names (most notably 'name')
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: ShowsDB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          client-showsdb:
            provider: spring
            client-id: client-showsdb
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-showsdb
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug