FROM openjdk:21-jdk
LABEL org.opencontainers.image.authors="Andreas"
COPY target/showsdb-auth-server-0.0.1-SNAPSHOT.jar showsdb-auth-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","showsdb-auth-server-0.0.1-SNAPSHOT.jar"]